spring:
  cloud:
    gateway:
      routes:
#        - id: product-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/products/**
#        - id: user-service
#          uri: http://localhost:8082
#          predicates:
#            - Path=/api/users/**
#        - id: order-service
#          uri: http://localhost:8081
#          predicates:
#            - Path=/api/orders/**, /api/cart/**
#
#        - id: product-service
#          uri: lb://PRODUCTSERVICE
#          predicates:
#            - Path=/api/products/**
#        - id: user-service
#          uri: lb://USERSERVICE
#          predicates:
#            - Path=/api/users/**
#        - id: order-service
#          uri: lb://ORDERSERVICE
#          predicates:
#            - Path=/api/orders/**, /api/cart/**
#        - id: eureka-service
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/main
#          filters:
#            - SetPath=/
#        - id: eureka-service-static
#          uri: http://localhost:8761
#          predicates:
#            - Path=/eureka/**

#               Adding rewrite filter using yml

        - id: product-service
          uri: lb://PRODUCTSERVICE
          predicates:
            - Path=/products/**
          filters:
              - "RewritePath=/products(?<segment>/?.*),/api/products${segment}"
        - id: user-service
          uri: lb://USERSERVICE
          predicates:
            - Path=/users/**
          filters:
            - "RewritePath=/users(?<segment>/?.*),/api/users${segment}"
        - id: order-service
          uri: lb://ORDERSERVICE
          predicates:
            - Path=/orders/**, /cart/**
          filters:
            - "RewritePath=/(?<segment>/?.*),/api/${segment}"
        - id: eureka-service
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/main
          filters:
            - SetPath=/
        - id: eureka-service-static
          uri: http://localhost:8761
          predicates:
            - Path=/eureka/**



server:
  port: 8080

#
#logging:
#  level:
#    root: info
#    org.springframework.cloud.gateway.route.RouteDefinitionLocator: info
#    org.springframework.cloud.gateway: TRACE


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true



# properties for actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


  tracing:
    sampling:
      probability: 1.0