

spring:
#
#  #  Credentials for rabbitmq
#
#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

#  h2:
#    console:
#      enabled: true
#  datasource:
#    url: jdbc:h2:mem:test
#  jpa:
#    show-sql: true
#    hibernate:
#      ddl-auto: update


  datasource:
    url: jdbc:mysql://localhost:3306/microservices_ecommerce_productservice
    username: root
    password: root123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect



# properties for actuator



# properties for actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always


  tracing:
    sampling:
      probability: 1.0
#

server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
