spring:
  application:
    name: configserver



#the below are credentials for mysql database


  profiles:
    active: jdbc
  datasource:
    url: jdbc:mysql://localhost:3306/configdb
    username:
    password:
    driver-class-name:
  cloud:
    config:
      server:
        jdbc:
          sql: "SELECT PROP KEY,PROP_VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?"
          default-label: main

#  cloud:
#    config:
#      server:
#        git:
#          uri: https://github.com/Sandeepkumar3003/app-configuration
##          the below are used when accessing private repository
#          username: ${GIT_USER}
#          password: ${GIT_TOKEN}


server:
  port: 8888


#the below are credentials for mysql database
#
#spring:
#  profiles:
#    active: jdbc
#  datasource:
#    url: jdbc:mysql://localhost:3306/configdb
#    username:
#    password:
#    driver-class-name:
#  cloud:
#    config:
#      server:
#        jdbc:
#          sql: "SELECT PROP KEY,PROP_VALUE from PROPERTIES where APPLICATION=? and PROFILE=? and LABEL=?"
#          default-label: main